version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build vue
          command: npm build
      - run:
          name: Install gh-pages and configure git
          command: |
            npm install gh-pages --save-dev
            git config user.email "horan116@gmail.com"
            git config user.name "stephenhoran"
      - run:
          name: Deploy build to gh-pages branch
          command: './node_modules/.bin/gh-pages --dotfiles --message "Deployment from $CIRCLE_SHA1" -d dist'